package name.benshepley.euler.problems.set1;

import name.benshepley.euler.framework.Solvable;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/*  Problem 2: https://projecteuler.net/problem=2
    Even Fibonacci numbers
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class TestProblem2 {
    @Test
    public void evaluateProblem_2() {
        final String ANSWER = "4613732";
        Solvable problem = new Problem2();
        assertEquals(ANSWER, problem.getSolution());
    }
}
